### ISSUE TITLE
Services timeout when connecting to the database

### ISSUE THREAD

**Issue by andreastedile** [carlocorradini/graphmarket#157]
Timeout takes ~3 minutes to take place

**Comment by andreastedile** [comment]
To reproduce:
```
docker-compose -f docker-compose.dev.yml up
```
Wait ~3 minutes:
```
products_1           | 2021-01-27 19:59:41:169 ERROR 	Bootstrap error: connect ETIMEDOUT 192.168.80.2:5432
users_1              | 2021-01-27 19:59:41:169 ERROR 	Bootstrap error: connect ETIMEDOUT 192.168.80.2:5432
inventories_1        | 2021-01-27 19:59:41:170 ERROR 	Bootstrap error: connect ETIMEDOUT 192.168.80.2:5432
purchases_1          | 2021-01-27 19:59:41:171 ERROR 	Bootstrap error: connect ETIMEDOUT 192.168.80.2:5432
reviews_1            | 2021-01-27 19:59:41:172 ERROR 	Bootstrap error: connect ETIMEDOUT 192.168.80.2:5432
```

**Comment by andreastedile** [comment]
How to connect to the database from the outside (host):
Open the container port by specifying it in `ports`: 
```
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: graphmarket
    ports:
    - 5432:5432
    networks:
      db-net:
        ipv4_address: 192.168.80.2
```

Issue the following command:
```
psql -h localhost -p 5432 -d graphmarket -U user -w
```
Or:
```
 psql -h 192.168.80.2 -p 5432 -d graphmarket -U user -W
 ```

When prompted, insert the password (which, for now, is `password`).

Indeed, this works. Thus, why can't the services reach the database?
